// Copies the contract ABIs from Foundry's build output into sdk/abi.ts (never hand-written).
// Run after `forge build`: node sdk/scripts/export-abi.ts
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("../../", import.meta.url);
const contracts = [
  ["VerifierAllowlist", "verifierAllowlistAbi"],
  ["EmissionsClaimRegistry", "emissionsClaimRegistryAbi"],
] as const;

let out = "// Generated by sdk/scripts/export-abi.ts from contracts/out. Do not edit.\n";
for (const [name, ident] of contracts) {
  const artifact = JSON.parse(readFileSync(new URL(`contracts/out/${name}.sol/${name}.json`, root), "utf8"));
  out += `\nexport const ${ident} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
writeFileSync(new URL("sdk/abi.ts", root), out);
console.log("sdk/abi.ts written");
