// Generated by sdk/scripts/export-abi.ts from contracts/out. Do not edit.

export const verifierAllowlistAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "initialOwner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "watcher",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CRED_TYPE_LE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DEFAULT_ADMIN_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "WATCHER_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "addAuditor",
    "inputs": [
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct VerifierAllowlist.AuditorInput",
        "components": [
          {
            "name": "auditorAidHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "leiHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ecrSaidHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addVerifier",
    "inputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct VerifierAllowlist.VerifierInput",
        "components": [
          {
            "name": "leiHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "verifier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "leCredSaidHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "accreditationSaidHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "accreditedUntil",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "auditors",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "ecrSaidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "addedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "revokedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "credentialRecord",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "credType",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "credHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRoleAdmin",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hasRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "institutions",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "currentAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "leCredSaidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "accreditationSaidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "accreditedUntil",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "addedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "suspendedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "liftedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isAuthorizedAt",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "t",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInstitutionActiveAt",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isVerifierActiveAt",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "t",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "leiOfAddress",
    "inputs": [
      {
        "name": "addr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "boundAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unboundAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liftSuspension",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "callerConfirmation",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeAuditor",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rotateVerifierAddress",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newAddr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "suspendVerifier",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AuditorAdded",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "leiHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "ecrSaidHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AuditorRevoked",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "leiHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "revokedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleAdminChanged",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SuspensionLifted",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "liftedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VerifierAdded",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "accreditedUntil",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "accreditationSaidHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VerifierAddressRotated",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "oldAddr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newAddr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "rotatedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VerifierSuspended",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "suspendedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessControlBadConfirmation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AccessControlUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "neededRole",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AddressAlreadyBound",
    "inputs": [
      {
        "name": "addr",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AlreadyRevoked",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AlreadySuspended",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AuditorExists",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AuditorNotFound",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidExpiry",
    "inputs": [
      {
        "name": "validUntil",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidInput",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotActiveVerifier",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotSuspended",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "VerifierExists",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "VerifierNotFound",
    "inputs": [
      {
        "name": "leiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
] as const;

export const emissionsClaimRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "allowlist_",
        "type": "address",
        "internalType": "contract VerifierAllowlist"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "allowlist",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract VerifierAllowlist"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimShipment",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "batchKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "quantityKg",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "importerCommit",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "credScopes",
    "inputs": [
      {
        "name": "reportScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "credScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "claimedKg",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "latestReportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isValid",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isValidAt",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerReport",
    "inputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct EmissionsClaimRegistry.ReportInput",
        "components": [
          {
            "name": "reportKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "reportIdHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "reportScopeKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "credScopeKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "auditorAidHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "kelSeq",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "supplier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "supplierCommit",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "installationCommit",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "verifiedKg",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "supersedes",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "remainingKg",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint96",
        "internalType": "uint96"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reportIdUnboundAt",
    "inputs": [
      {
        "name": "reportScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "reportIdHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reportScopes",
    "inputs": [
      {
        "name": "reportScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "reportIdHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "latestReportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "boundAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reports",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct EmissionsClaimRegistry.ReportRecord",
        "components": [
          {
            "name": "verifier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "issuerLeiHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "auditorAidHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "kelSeq",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "supplier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "supplierCommit",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "installationCommit",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "verifiedKg",
            "type": "uint96",
            "internalType": "uint96"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "registeredAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "revokedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "reportIdHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "reportScopeKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "credScopeKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "supersedes",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "supersededBy",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "revokeReport",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "shipmentStatus",
    "inputs": [
      {
        "name": "batchKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "quantityKg",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "importerCommit",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "claimedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "reportValid",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "shipments",
    "inputs": [
      {
        "name": "batchKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "quantityKg",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "importerCommit",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "claimedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ReportRegistered",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "supplier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "issuerLeiHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "reportScopeKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "credScopeKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "reportIdHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "kelSeq",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "verifiedKg",
        "type": "uint96",
        "indexed": false,
        "internalType": "uint96"
      },
      {
        "name": "validUntil",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReportRevoked",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "revokedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReportSuperseded",
    "inputs": [
      {
        "name": "oldReportKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newReportKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "credScopeKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "carriedClaimedKg",
        "type": "uint96",
        "indexed": false,
        "internalType": "uint96"
      },
      {
        "name": "newVerifiedKg",
        "type": "uint96",
        "indexed": false,
        "internalType": "uint96"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ShipmentClaimed",
    "inputs": [
      {
        "name": "batchKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reportKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "supplier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "quantityKg",
        "type": "uint96",
        "indexed": false,
        "internalType": "uint96"
      },
      {
        "name": "importerCommit",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "cumulativeClaimedKg",
        "type": "uint96",
        "indexed": false,
        "internalType": "uint96"
      },
      {
        "name": "claimedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyRevoked",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AuditorNotAuthorized",
    "inputs": [
      {
        "name": "auditorAidHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BatchAlreadyClaimed",
    "inputs": [
      {
        "name": "batchKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CredScopeAlreadyCovered",
    "inputs": [
      {
        "name": "credScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "latestReportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExceedsVerifiedTonnage",
    "inputs": [
      {
        "name": "remainingKg",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "requestedKg",
        "type": "uint96",
        "internalType": "uint96"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidExpiry",
    "inputs": [
      {
        "name": "validUntil",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidInput",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotActiveVerifier",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotReportIssuer",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "issuerLeiHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotSupplier",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PeriodAlreadyCovered",
    "inputs": [
      {
        "name": "reportScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "currentReportIdHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReportExists",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReportIdRetired",
    "inputs": [
      {
        "name": "reportScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "reportIdHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReportInvalid",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReportNotFound",
    "inputs": [
      {
        "name": "reportKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SupersedeMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "given",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SupersedeOverClaimed",
    "inputs": [
      {
        "name": "credScopeKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "claimedKg",
        "type": "uint96",
        "internalType": "uint96"
      },
      {
        "name": "verifiedKg",
        "type": "uint96",
        "internalType": "uint96"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroQuantity",
    "inputs": []
  }
] as const;
